# Jekyll
theme: linkhub-jekyll-theme

# Site Configuration
name: Yuugi  # Name of your website
tagline: Links  # Set your preferred page title
description: This is just a collection of random links about what I do and where I can be found :)  # Also used as a meta description
favicon:
  path: https://fudi.yuugi.dev/media/a9bfcfe9278f52676be23df40d31c69acb238ef5a528705da7c31c4c7625d2b1.jpg # Path / URL to the favicon of your website (e.g., 'assets/images/favicon.png')
  type: jpeg # File format of image. Change according to your image. Supported types: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types
logo: https://fudi.yuugi.dev/media/a9bfcfe9278f52676be23df40d31c69acb238ef5a528705da7c31c4c7625d2b1.jpg # Path / URL to the logo (e.g., 'assets/images/logo.png')
url: https://yuugi.dev # URL of your website
locale: en_GB # The value specifies the locale in which these tags are marked up. It follows the format `language_TERRITORY`.
ga4: # Google Analytics 4 measurement ID, for e.g. G-XXXXXXX (optional). Remove it if it’s not needed.
twitter:
  username: mar0xy # Used for SEO
image:
  path: assets/77ba63c0f023cad2a9c2d515777bb227826660a699c2b8d0c6909172b130e814.jpg # Used for SEO (og:image, twitter:image)
  type: jpeg # File format of image.
  height: 1995 # Pixels
  width: 1275
  alt: logo

# Verified Badge Configuration
badge:
  enable: true # Set to 'true' or 'false' to enable / disable the badge
  icon: ri:verified-badge-fill  # Enter the icon name for the badge from Iconify Design (https://icon-sets.iconify.design/)
  color: '#dfb221'  # Define the color of the badge
 
# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"    

# Exclude
exclude: [README.md, Gemfile.lock, .jekyll-cache/, .github/, CHANGELOG.md, Gemfile, LICENSE.txt, funding.yml, linkhub-jekyll-theme.gemspec]
